### ISSUE TITLE
Single quotes are changed to double quotes when pushed to Sphinx from Weblate

### ISSUE THREAD

**Issue by CooperVR69** [vircadia/vircadia-docs-sphinx#112]
Single quotes ' are changed to double quotes " when translations are pushed from Weblate to Sphinx.
For the French translation this is a problem as single quotes are commonly used as a character within sentences.
This issue started to come up since Jan 28, older translations were puhsed through fine.
Therefore I am wondering if it is related to a recent version upgrade, but not sure.

**Comment by JulianGro** [comment]
This seems to be an issue with Sphinx, as the file that comes from Weblate uses a single quote as expected.
