### ISSUE TITLE
"Edit on Github" links are broken

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-docs-sphinx#114]
Broken: `https://github.com/vircadia/vircadia-docs-sphinx//master/docs/source/host/add-content.rst`
Should be: `https://github.com/vircadia/vircadia-docs-sphinx/tree/master/docs/source/host/add-content.rst`

**Comment by JulianGro** [comment]
Yeah I have no idea why this is happening for now.
Not only did it work in the past, but if I build master it generates the right URLs (e.g. ``https://github.com/vircadia/vircadia-docs-sphinx/blob/master/docs/source/developer.rst``)
