### ISSUE TITLE
Package Script Docs need to be imported to Developer Section

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-docs-sphinx#144]

**Comment by JulianGro** [comment]
After taking a closer look at it, I don't think it makes much sense to include the https://github.com/vircadia/vircadia/blob/master/pkg-scripts/README.md
It is made to explain what it in that particular folder, most of it's information is already in https://github.com/vircadia/vircadia/tree/master/pkg-scripts and the information only really is useful when you are looking at the package scripts in the first place.
