### ISSUE TITLE
Slow scrolling in docs

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia-docs-sphinx#183]
There is a weird issue with the scrolling on the [user doc's](https://docs.vircadia.com/) site.
If the sidebar is longer than the window it affects the scrolling in the main window, it tries to scroll both but does it painfully slow, until you reach the bottom or top of the sidebar.

1. expand "Create > Avatars" in the sidebar (it's a long one).
2. make the window short enough that the sidebar is now too long for the window.
3. with cursor in the main panel,  scrolling down or up should be really slow, scrolling with the cursor in the sidebar panel works as expected.

Tested in Chrome and Edge, API docs does not have this issue.

**Comment by JulianGro** [comment]
Please report this issue to Chrome and Edge as this is fairly obviously an issue with their browsers. It sounds like some broken hardware acceleration and/or smoothing.

Vivaldi and Firefox on Linux have no such issue even with smoothing enabled.

**Comment by Gigabyte5671** [comment]
Tested this just now in Chrome `104`, Edge `104`, and FireFox `104`. It appears that this issue no longer persists.
