### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by hoonoon** [vircadia/vircadia-docs-sphinx#188]
I would like to proceed with the Korean.
Do you mind if i proceed with the work?

**Comment by JulianGro** [comment]
Sorry for seeing this so late. I will add Korean language support to Weblate and the automatic builds.
Are you on Discord? We can talk to each other directly if there is any questions that way.

**Comment by JulianGro** [comment]
@hoonoon Korean translation support has been added to Weblate and the documentation https://weblate.vircadia.dev/engage/vircadia-documentation/ko/
