### ISSUE TITLE
Update blendshape documentation

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia-docs-sphinx#58]
With the addition of blendshapes on entities I found it not entirely clear that that you need to use one of the predefined names for it to work.
https://github.com/kasenvr/project-athena/blob/master/libraries/shared/src/BlendshapeConstants.h

I suggest updating: https://docs.vircadia.dev/create/avatars/avatar-standards.html#blendshapes
(for example, it is missing the user blend shapes and the ARkit ones).

And then put a link to that in the _blendshapeCoefficients_ section of: https://apidocs.vircadia.dev/Entities.html#.EntityProperties-Model

like in https://apidocs.vircadia.dev/MyAvatar.html#.setBlendshape

**Comment by ctrlaltdavid** [comment]
Blendshape names are per the strings in BlendshapeConstants.cpp.
Backing enums are in BlendshapeConstants.h.

The ARkit blendshape support was added in HiFi PR 16400, merged 18 Nov 2019. This PR made some of the original blendshapes legacy or deprecated.

NEW blendshapes:
MouthClose
MouthUpperUp_L
MouthUpperUp_R
MouthLowerDown_L
MouthLowerDown_R
MouthPress_L
MouthPress_R
MouthShrugLower
MouthShrugUpper
NoseSneer_L
NoseSneer_R
TongueOut

Legacy blendshapes:
LipsUpperUp - maps to MouthUpperUp_L and MouthUpperUp_R
LipsLowerDown - maps to MouthLowerDown_L and MouthLowerDown_R
Sneer - maps to NoseSneer_L and NoseSneer_R
JawChew - deprecated
ChinLowerRaise - deprecated
ChinUpperRaise - deprecated

**Comment by Colorfingers** [comment]
This is great!  Now I can support each and every one!  Thanks David!

**Comment by daleglass** [comment]
Dev meeting: the above needs getting added to the docs

**Comment by SilverfishVR** [comment]
Fixed in https://github.com/vircadia/vircadia-docs-sphinx/pull/171
