### ISSUE TITLE
Document environment variables useful during development

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia-docs-sphinx#62]
Including:
- HIFI_USE_SOURCE_TREE_RESOURCES
- HIFI_DEBUG_OPENVR
- ...

**Comment by kasenvr** [comment]
Very good idea. :) The source trees are especially important for anyone working on QML.

**Comment by ctrlaltdavid** [comment]
There are other environment variables, too. For example, search for the following in the codebase:
```
QProcessEnvironment::systemEnvironment().contains
```

**Comment by JulianGro** [comment]
I cannot transfer this issue to https://github.com/vircadia/vircadia-dev-docs
