### ISSUE TITLE
Assignment Client CLI will need update

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia-docs-sphinx#77]
https://docs.vircadia.dev/developer/assignment-client/command-line-parameters.html will need an update once https://github.com/kasenvr/project-athena/pull/666 is merged.

**Comment by odysseus654** [comment]
The --wallet option would be dropped by #666

While forming this patch I also realized that the -a and -p parameters were being looked at if/only if --wallet was specified.  This is fixed on both #666 and in https://github.com/kasenvr/project-athena/pull/667

**Comment by JulianGro** [comment]
This needs to be addressed in the new development repo https://github.com/vircadia/vircadia-dev-docs
I am closing this as these kinds of (probably far) future issues don't seem very useful.
